### ISSUE TITLE
`simple` theme isn't working - Uncaught ReferenceError: lightdm is not defined

### ISSUE THREAD

**Issue by tuurep** [JezerM/web-greeter-themes#2]
Hello! Using the AUR package `web-greeter`,
```
$ web-greeter -v
3.5.1
```

I have tried and confirmed that the themes `gruvbox` and `dracula` work and I can login to my Openbox session with those. Looks like something is missing for the `simple` theme.

`$ web-greeter --debug` gives the error box:

```
web-greeter://app/usr/share/web-greeter/themes/simple/index.html 207: Uncaught ReferenceError: lightdm is not defined
```

Lines in question in `index.html`:

```
206	window.addEventListener("GreeterReady", () => {
207		lightdm.show_message.connect(show_message)
208		lightdm.show_prompt.connect(show_prompt)
209		lightdm.authentication_complete.connect(authentication_complete)
210		lightdm.autologin_timer_expired.connect(autologin_timer_expired)
211
212		start_authentication()
213	});
```

I found out that you can get rid of this error by copying `_vendor/js/jquery.min.js` from the older, abandoned `lightdm-webkit2-greeter`:

```
$ sudo cp /usr/share/lightdm-webkit/themes/_vendor/js/jquery.min.js /usr/share/web-greeter/_vendor/js/
```

The reason I found that out is because I've been trying to make my custom lightdm-webkit2-theme compatible with your fork, but ran into an issue where the theme tries to source `_vendor/js/jquery.min.js` but it's not there in the new `web-greeter`. Also, folder `_vendor` is one level up in `web-greeter` relative to `lightdm-webkit2-greeter` where it's inside the `themes` folder.

The theme I'm trying to use is here:
https://github.com/tuurep/dmg_black
which is a fork of this (to customize the colors):
https://github.com/davidmogar/lightdm-webkit2-dmg_blue

However while copying the `jquery.min.js` to `web-greeter` gets rid of the `Uncaught ReferenceError` errors, I can't log in either in `simple` or `dmg_black`.
 
Perhaps it's related to the updated API and the js parts of the themes need to be updated?

**Comment by JezerM** [comment]
I will check it out soon~

The simple theme hasn't been updated in a long time, so it's expected to have API bugs (which I should have solved). jQuery was removed a long time ago, even when Simple theme was working, so it's not required by any default theme.

**Comment by tuurep** [comment]
Ah, thanks. I was unsure if all lightdm-webkit2-themes should just work on this updated fork, or if they can have deprecated stuff. I have to learn how to update dmg_black, should be doable by referencing your gruvbox and dracula themes and the API docs. Thought the `simple` theme could be useful to reference, which is why I found out that's outdated in the first place :smiley:

**Comment by JezerM** [comment]
Seems it wasn't a Simple theme's error but an issue regarding to web-greeter's event handling. The `GreeterReady` event was being fired before the LightDM API was ready and so the `lightdm` object didn't exist on startup.

This should be fixed in latest web-greeter's commit: https://github.com/JezerM/web-greeter/commit/7be6017abc92f22da470edf4bb8f5913215ae26d.

**Comment by JezerM** [comment]
Also, about your dmg_black theme, you must include the jQuery library within your theme as jQuery was removed in web-greeter v3.0.0.

**Comment by tuurep** [comment]
Thank you :smiley:

I tried confirming that Simple theme works with the latest build, and while it does get rid of the lightdm ReferenceError, another issue remains:

(Output from `web-greeter --debug`)

```
2022-10-17 00:32:24 [ ERROR ] Greeter - Greeter.py:379 : start_session | lightdm_greeter_error: Session returned error code 1 (2)
Traceback (most recent call last):
  File "/usr/lib/web-greeter/bridge/Greeter.py", line 373, in start_session
    started: bool = LightDMGreeter.start_session_sync(session)
gi.repository.GLib.GError: lightdm_greeter_error: Session returned error code 1 (2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/web-greeter/bridge/Greeter.py", line 381, in start_session
    globales.greeter.window,
AttributeError: 'Browser' object has no attribute 'window'. Did you mean: 'windows'?
/usr/bin/web-greeter: line 2:  1545 Aborted                 (core dumped) python3 /usr/lib/web-greeter $@
```

Taking a guess from the error message that `window` could be a typo and should be `windows`, I tried editing that in `web-greeter/src/bridge/Greeter.py` line 381 and building again. That will result in a different error message with `web-greeter --debug`:

```
2022-10-17 00:44:17 [ ERROR ] Greeter - Greeter.py:379 : start_session | lightdm_greeter_error: Session returned error code 1 (2)
Traceback (most recent call last):
  File "/usr/lib/web-greeter/bridge/Greeter.py", line 373, in start_session
    started: bool = LightDMGreeter.start_session_sync(session)
gi.repository.GLib.GError: lightdm_greeter_error: Session returned error code 1 (2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/web-greeter/bridge/Greeter.py", line 380, in start_session
    general_error_prompt(
  File "/usr/lib/web-greeter/browser/error_prompt.py", line 149, in general_error_prompt
    dialog = Dialog(parent = window,
  File "/usr/lib/web-greeter/browser/error_prompt.py", line 124, in __init__
    super().__init__(parent)
TypeError: QDialog(parent: QWidget = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.WindowFlags()): argument 1 has unexpected type 'list'
/usr/bin/web-greeter: line 2:  3107 Aborted                 (core dumped) python3 /usr/lib/web-greeter $@
```

Note: both times the error happens after pressing enter to send (correct) password

**Comment by JezerM** [comment]
Yep, it's a typo. I fixed it in latest commit. However, the reason this is happening is because of LightDM settings. The default session for LightDM is `default`, so web-greeter will fail to start the session named `default` as there is no session named like that.

**Comment by JezerM** [comment]
You could set `user-session=xfce` in `lightdm.conf` for instance to avoid this issue.

**Comment by tuurep** [comment]
Oh, that makes perfect sense. Thanks a lot.

`user-session=openbox` allows me to login with Simple, but `web-greeter --debug` doesn't get that value from my `lightdm.conf` I suppose.

I can imagine users make this mistake a lot, sorry about that.. :satisfied:

**Comment by JezerM** [comment]
Hmm, perhaps you're setting the `user-session` inside an specific Seat config like: `[Seat:seat0]`. You must set it below `[Seat:*]`. If it does still fails to use your defined session, you could try to restart the LightDM service :D

**Comment by tuurep** [comment]
Yep it was under `[Seat:*]`

Restarting lightdm didn't get rid of errors for `--debug`, but again the login worked in the real-case scenario. I'm quite happy with this but if you think running the debug option has a bug regarding this, let me know if I can do anything else.

**Comment by JezerM** [comment]
Well, the debug mode is essentially the same as the normal mode but with some additions, so this shouldn't be happening. It's weird, but if you're happy and Ok with it, so be it~

Thanks for taking your time with this issue, it really helps!

**Comment by tuurep** [comment]
Yea it does seem like deceiving errors. Let me know any time if I can help you troubleshoot/fix it.

dmg_black:

Added jquery per your suggestion but now the theme can't seem to get list of users correctly, shows only one user which is 'Undefined' :smiley:

Don't feel obligated to help debug this old project, but maybe if you know off the top of your head, I thought I'd mention.

**Comment by JezerM** [comment]
> Added jquery per your suggestion but now the theme can't seem to get list of users correctly, shows only one user which is 'Undefined' 😃

xD. I will check it out.

Anyways this issue will be closed, thanks.

**Comment by tuurep** [comment]
Thank you :)
